server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: msvc-solicitud
          uri: lb://MSVC-SOLICITUD
          predicates:
            - Path=/solicitudes/**
        - id: msvc-asignaciones
          uri: lb://MSVC-ASIGNACIONES
          predicates:
            - Path=/asignaciones/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/